/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-tournament` | `/create-tournament`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-org` | `/create-org`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/join` | `/join`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-team` | `/create-team`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/my-tournaments` | `/my-tournaments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/tournament/[id]` | `/tournament/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(auth)'}/team/[id]` | `/team/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create-tournament` | `/create-tournament`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create-org` | `/create-org`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/join` | `/join`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create-team` | `/create-team`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/my-tournaments` | `/my-tournaments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/tournament/[id]` | `/tournament/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(auth)'}/team/[id]` | `/team/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/sign-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create-tournament${`?${string}` | `#${string}` | ''}` | `/create-tournament${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create-org${`?${string}` | `#${string}` | ''}` | `/create-org${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/join${`?${string}` | `#${string}` | ''}` | `/join${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create-team${`?${string}` | `#${string}` | ''}` | `/create-team${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/my-tournaments${`?${string}` | `#${string}` | ''}` | `/my-tournaments${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/teams${`?${string}` | `#${string}` | ''}` | `/teams${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-tournament` | `/create-tournament`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-org` | `/create-org`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/join` | `/join`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-team` | `/create-team`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/my-tournaments` | `/my-tournaments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownInputParams; } | `${'/(auth)'}/tournament/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tournament/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/team/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/team/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(auth)'}/tournament/[id]` | `/tournament/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(auth)'}/team/[id]` | `/team/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
